<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Daily Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .page-break {
            page-break-after: always;
        }

        .report-table th,
        .report-table td {
            padding: 4px;
            border: 1px solid #666;
            text-align: left;
            word-wrap: break-word;
            max-width: 150px;
            font-size: 12px !important;
        }

        .report-table th,
        tfoot {
            background: lightgray;
            font-weight: bold;
            font-size: 12px !important;
        }

        .report-table {
            width: 100%;
            border-collapse: collapse;

        }


        .uk-label {
            padding: 4px 6px;
            border-radius: 4px;
            color: #fefefe;
        }

        .uk-label-primary {
            background-color: #007bff;
        }

        .uk-label-success {
            background-color: #28a745;
        }

        .uk-label-danger {
            background-color: #dc3545;
        }

        .uk-label-info {
            background-color: #17a2b8;
        }

        .uk-label-secondary {
            background-color: #081607;
        }

        .uk-label-amber {
            background-color: #F59E0B;
        }

        .uk-background-default {
            background-color: #f2f2f2;
        }

        .uk-background-amber {
            background-color: #F59E0B;
        }

        .empty-row {
            text-align: center;
            font-style: italic;
            color: #888;
        }

        .header {
            width: 100%;
            display: table;
            margin-bottom: 20px;
        }

        .left-content,
        .center-content,
        .right-content {
            display: table-cell;
            vertical-align: middle;
            padding: 10px;
        }

        .left-content {
            width: 33%;
            text-align: left;
            margin-top: 10px;
        }

        .center-content {
            width: 33%;
            text-align: center;
        }

        .right-content {
            width: 33%;
            text-align: right;
            margin-top: 10px;
        }

        .logo {
            max-width: 100px;
            height: auto;
            margin-bottom: 10px;
        }

        .company-description {
            font-size: 14px;
            color: #666;
        }

        .report-title {
            font-size: 18px;
            font-weight: bold;
            margin: 10px 0;
        }

        .page-number {
            font-size: 14px;
            color: #666;
        }

    </style>
</head>


<body>
    <div class="header">
        <div class="left-content">
            <p class="company-description">Generated by {{ ucfirst(auth()->user()->firstname) }} <br> {{ now() }}
            </p>
        </div>
        <div class="center-content">
            <h1 class="report-title">Daily Report</h1>
        </div>
        <div class="right-content">
            <p class="page-number">Page 1 of 1</p>
            <p class="page-number">Date: {{ date('d/m/Y') }}</p>
        </div>
    </div>
    @php
        $totalUnits = 0;
        $totalDuration = \Carbon\CarbonInterval::create(0, 0, 0, 0); // Initialize the totalDuration as a CarbonInterval;
        $totalUnitshr = 0;

        $totalProjects = 0;
        $totalTasks = 0;

        $aboveTarget = 0;
        $belowTarget = 0;
        $onTarget = 0;
    @endphp
    <div>
        <table class="report-table">
            <thead>
                <tr>

                    <th style="width: 10%">Project</th>
                    <th style="width: 10%">Task</th>
                    <th style="width: 10%">Type</th>
                    <th style="width: 10%">Units</th>
                    <th style="width: 10%">Duration</th>
                    <th style="width: 10%">Units/hr</th>
                    <th style="width: 10%">Perfomance</th>
                    <th style="width: 10%">Start</th>
                    <th style="width: 10%">End</th>
                    <th style="width: 10%">Date</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($reports as $report)
                    @php
                        $totalUnits += $report->task->unit_type->name === 'HOUR' ? 0 : (int) $report->units_completed;
                        $totalUnitshr += $report->hourlyRate;
                        $totalDuration = $totalDuration->add($report->duration); // Add the durations together

                        $totalProjects++;
                        $totalTasks++;

                        // calculate above & below targets

                        if ($report->perfomance['color'] === 'green') {
                            $aboveTarget++;
                        } elseif ($report->perfomance['color'] === 'red') {
                            $belowTarget++;
                        }elseif($report->performance['color'] === 'blue'){
				            $onTarget++;
						}

                    @endphp
                    <tr>

                        <td>
                            <a
                                href="{{ route('projects.tasks.show', $report->project->slug) }}">{{ ucfirst($report->project->name) }}</a>
                        </td>
                        <td>{{ ucfirst($report->task->name) }}</td>
                        <td>
                            <span style="font-size:12px;"
                                class="uk-label uk-label-{{ $report->task->unit_type->color() }}">
                                {{ $report->task->unit_type->name }}
                            </span>
                        </td>
                        <td>
                            @if ($report->task->unit_type->name === 'HOUR')
                                N/A
                            @else
                                {{ $report->units_completed }}
                            @endif

                        </td>
                        <td>
                            @if ($report->task->unit_type->name === 'HOUR')
                                <span style="font-size:12px;">{{ number_format($report->duration->totalMinutes, 2) }}
                                    mins</span>
                            @else
                                {{ $report->duration->forHumans(['short' => true]) }}
                            @endif

                        </td>
                        <td>
                            @if ($report->reported_at > new \DateTime())
                                Pending {{ $report->hourlyRate == 0 ? 'N/A' : $report->hourlyRate }}
                            @else
                                {{ $report->hourlyRate == 0 ? 'N/A' : $report->hourlyRate }}
                            @endif
                        </td>

                        <td>

                            <span class="" style="color: {{ $report->perfomance['color'] }}">
                                {{ $report->perfomance['status'] }}
                            </span><br>
                            <span class="uk-text-small">Target: {{ $report->task->target }}
                                <span> {{ $report->formattedTarget }} </span></span>
                        </td>

                        <td>{{ $report->started_at->format('H:i:s') }}</td>
                        <td>{{ $report->ended_at->format('H:i:s') }}</td>
                        <td>{{ $report->reported_at->format('d/m/Y') }}</td>

                    </tr>

                @empty
                    <tr class="empty-row">
                        <td colspan="9">You don't have any reports at the moment</td>
                    </tr>
                @endforelse
            </tbody>
            <tfoot style="font-size:12px;">
                <tr style="font-weight: 800">

                    <td>Total:{{ $totalProjects <= 0 ? 'N/A' : $totalProjects }} </td>
                    <td>Total:{{ $totalTasks <= 0 ? 'N/A' : $totalTasks }}</td>
                    <td></td>
                    <td>Total:{{ $totalUnits <= 0 ? 'N/A' : $totalUnits }}</td>
                    <td>Total:{{ $totalDuration->forHumans(['short' => true]) }}</td>
                    <td>Total:{{ $totalUnitshr <= 0 ? 'N/A' : $totalUnitshr }} </td>
                            
                        <td>Above: {{ $aboveTarget ?? 'N/A' }}</td>
                        <td>Below: {{ $belowTarget ?? 'N/A' }}</td>
                    <td>On Target: {{ $onTarget ?? 'N/A' }}</td>
                    <td></td>
                    

                </tr>
        </table>
    </div>
</body>

</html>
