<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Daily Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .page-break {
            page-break-after: always;
        }

        .report-table th,
        .report-table td {
            padding: 4px;
            text-align: left;
            border: 1px solid #ddd;
            word-wrap: break-word;
            max-width: 150px;
            font-size: 14px;
           /* overflow: hidden; */
        }

        .report-table th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        .report-table {
            width: 100%;
            border-collapse: collapse;
        }

        .report-table th,
        .report-table td {
            padding: 4px;
            text-align: left;
            border: 1px solid #ddd;
        }

        .report-table th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        .uk-label {
            padding: 4px 6px;
            border-radius: 4px;
            color: #fefefe;
        }

        .uk-label-primary {
            background-color: #007bff;
        }

        .uk-label-success {
            background-color: #28a745;
        }

        .uk-label-danger {
            background-color: #dc3545;
        }

        .uk-label-info {
            background-color: #17a2b8;
        }

        .uk-label-secondary {
            background-color: #081607;
        }

        .uk-background-default {
            background-color: #f2f2f2;
        }
        .uk-background-amber{
            background-color: #F59E0B;
        }

        .empty-row {
            text-align: center;
            font-style: italic;
            color: #888;
        }

         .header {
            width: 100%;
            display: table;
            margin-bottom: 20px;
        }

        .left-content,
        .center-content,
        .right-content {
            display: table-cell;
            vertical-align: middle;
            padding: 10px;
        }

        .left-content {
            width: 33%;
            text-align: left;
        }

        .center-content {
            width: 33%;
            text-align: center;
        }

        .right-content {
            width: 33%;
            text-align: right;
        }

        .logo {
            max-width: 100px;
            height: auto;
            margin-bottom: 10px;
        }

        .company-description {
            font-size: 14px;
            color: #666;
        }

        .report-title {
            font-size: 18px;
            font-weight: bold;
            margin: 10px 0;
        }

        .page-number {
            font-size: 14px;
            color: #666;
        }
    </style>
</head>


<body>
    <div class="header">
        <div class="left-content">
            <p class="company-description">Generated by {{auth()->user()->firstname }} <br> {{ now() }}</p>
        </div>
        <div class="center-content">
            <p class="company-description">Productivity Reporting System</p>
            <h1 class="report-title">Daily Report</h1>
        </div>
        <div class="right-content">
            <p class="page-number">Page 1 of 1</p>
            <p class="page-number">Date: {{ date('d/m/Y') }}</p>
        </div>
    </div>
      @php
        $totalCompletedTasks = 0;
        $totalDuration = \Carbon\CarbonInterval::create(0, 0, 0, 0); // Initialize the totalDuration as a CarbonInterval;
        $totalUnitshr = 0;
    @endphp
    <div>
        <table class="report-table">
            <thead>
                <tr>
                    
                    <th style="width: 10%">Project</th>
                    <th style="width: 10%">Task</th>
                    <th style="width: 10%">Unit type</th>
                    <th style="width: 10%">Completed Tasks</th>
                    <th style="width: 10%">Duration</th>
                    <th style="width: 10%">Units/hr</th>
                    <th style="width: 10%">Perfomance</th>
                    <th style="width: 10%">Start</th>
                    <th style="width: 10%">End</th>
                    <th style="width: 10%">Date</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($reports as $report)
                    @php
                        $totalCompletedTasks += $report->units_completed;
                        $totalUnitshr += $report->hourlyRate;
                        $totalDuration = $totalDuration->add($report->duration); // Add the durations together
                    @endphp
                    <tr>
                       
                        <td>
                            <a href="{{ route('projects.tasks.show', $report->project->slug) }}">{{ ucfirst($report->project->name) }}</a>
                        </td>
                        <td>{{ ucfirst($report->task->name) }}</td>
                        <td>
                            <span class="uk-label uk-label-{{ $report->task->unit_type->color() }}">
                                {{ $report->task->unit_type->name }}
                            </span>
                        </td>
                        <td>{{ $report->units_completed }} </td>
                        <td>{{ $report->duration->forHumans(['short' => true]) }}</td>
                        <td>
                            {{ $report->hourlyRate }}
                        <td>


                            @php
                                // Get the individual target for this associate
                                $individualTarget = $report->task->target;
                                
                                // Initialize variables
                                $percentageDifference = 0;
                                $performanceStatus = '';
                                $color = '';
                                
                                // Check if $individualTarget is not zero
                                if ($individualTarget != 0) {
                                    // Calculate the percentage difference from the target
                                    $percentageDifference = number_format((($report->hourlyRate - $individualTarget) / $individualTarget) * 100, 1);
                                
                                    // Determine if performance is above or below the target
                                    if ($percentageDifference > 0) {
                                        $performanceStatus = 'Perfomance: ' . $percentageDifference;
                                        $color = 'green';
                                    } elseif ($percentageDifference < 0) {
                                        $performanceStatus = 'Perfomance: ' . abs($percentageDifference);
                                        $color = 'red';
                                    } else {
                                        $performanceStatus = 'On Target';
                                        $color = 'blue';
                                    }
                                } else {
                                    // Handle the case where $individualTarget is zero
                                    $performanceStatus = 'Target is Zero';
                                    $color = 'gray';
                                }
                            @endphp
                            <span class="" style="color: {{ $color }}"> 
                               {{ $performanceStatus }}
                            </span><br>
                            <span class="uk-text-small">Target: {{ $report->task->target }}</span>
                        </td>
                        <td>{{ $report->started_at->format('H:i:s') }}</td>
                        <td>{{ $report->ended_at->format('H:i:s') }}</td>
                        <td>{{ $report->reported_at->format('d/m/Y') }}</td>
                      
                    </tr>

                @empty
                    <tr class="empty-row">
                        <td colspan="9">You don't have any reports at the moment</td>
                    </tr>
                @endforelse
            </tbody>
            <tfoot>
                <tr>

                    <td style="font-weight: 800" colspan="3">Total Completed Tasks: {{ $totalCompletedTasks }}
                    </td>
                    <td style="font-weight: 800" colspan="3">Total Duration: {{ $totalDuration }}
                    </td>
                    <td style="font-weight: 800" colspan="3">Total Units/hr: {{ $totalUnitshr }} </td>
                   {{-- @if (auth()->user()->isAdmin() ||
                            auth()->user()->isProjectManager())
                        <td style="font-weight: 800" colspan="2">On Target: {{ 'X' }}
                        </td>
                        <td style="font-weight: 800" colspan="2">Below Target: {{ 'Y' }}
                        </td>
                    @endif --}}
                </tr>
            </tfoot>
        </table>
    </div>
</body>

</html>
