<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Daily Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .page-break {
            page-break-after: always;
        }

        .report-table th,
        .report-table td {
            padding: 8px;
            text-align: left;
            border: 1px solid #ddd;
            word-wrap: break-word;
            max-width: 200px;
            overflow: hidden;
        }

        .report-table th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        .report-table {
            width: 100%;
            border-collapse: collapse;
        }

        .report-table th,
        .report-table td {
            padding: 8px;
            text-align: left;
            border: 1px solid #ddd;
        }

        .report-table th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        .uk-label {
            padding: 5px 8px;
            border-radius: 4px;
            color: #fefefe;
        }

        .uk-label-primary {
            background-color: #007bff;
        }

        .uk-label-success {
            background-color: #28a745;
        }

        .uk-label-danger {
            background-color: #dc3545;
        }

        .uk-label-info {
            background-color: #17a2b8;
        }

        .uk-label-secondary {
            background-color: #081607;
        }

        .uk-background-default {
            background-color: #f2f2f2;
        }
        .uk-background-amber{
            background-color: #F59E0B;
        }

        .empty-row {
            text-align: center;
            font-style: italic;
            color: #888;
        }

         .header {
            width: 100%;
            display: table;
            margin-bottom: 20px;
        }

        .left-content,
        .center-content,
        .right-content {
            display: table-cell;
            vertical-align: middle;
            padding: 10px;
        }

        .left-content {
            width: 33%;
            text-align: left;
        }

        .center-content {
            width: 33%;
            text-align: center;
        }

        .right-content {
            width: 33%;
            text-align: right;
        }

        .logo {
            max-width: 100px;
            height: auto;
            margin-bottom: 10px;
        }

        .company-description {
            font-size: 14px;
            color: #666;
        }

        .report-title {
            font-size: 18px;
            font-weight: bold;
            margin: 10px 0;
        }

        .page-number {
            font-size: 14px;
            color: #666;
        }
    </style>
</head>


<body>
    <div class="header">
        <div class="left-content">
            <p class="company-description">Generated by {{auth()->user()->firstname }} <br> {{ now() }}</p>
        </div>
        <div class="center-content">
            <p class="company-description">Productivity Reporting System</p>
            <h1 class="report-title">Daily Report</h1>
        </div>
        <div class="right-content">
            <p class="page-number">Page 1 of 1</p>
            <p class="page-number">Date: {{ date('d/m/Y') }}</p>
        </div>
    </div>
    <div class="uk-overflow-auto">
        <table class="report-table">
            <thead>
                <tr>
                    <th>Project</th>
                    <th>Task</th>
                    <th>Unit Type</th>
                    <th>Completed Tasks</th>
                    <th>Duration</th>
                    <th>Units/hr</th>
                    <th>Start</th>
                    <th>End</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($reports as $report)
                    <tr>
                        <td>{{ ucfirst($report->project->name) }}</td>
                        <td>{{ ucfirst($report->task->name) }}</td>
                        <td>
                            <span class="uk-label uk-label-{{ $report->task->unit_type->color() }}">
                                {{ $report->task->unit_type->name }}
                            </span>
                        </td>
                        <td>{{ $report->units_completed }}</td>
                        <td>{{ $report->duration }}</td>
                        <td>{{ $report->hourlyRate }}</td>
                        <td>{{ $report->started_at->format('H:i:s') }}</td>
                        <td>{{ $report->ended_at->format('H:i:s') }}</td>
                        <td>{{ $report->reported_at->format('d/m/Y') }}</td>
                    </tr>
                @empty
                    <tr class="empty-row">
                        <td colspan="9">You don't have any reports at the moment</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>
</body>

</html>
